version: '3.8'

services:
  core-banking-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banking-net

  core-banking-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-banking-db:5432/banking
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: securepass
    depends_on:
      core-banking-db:
        condition: service_healthy
    networks:
      - banking-net

volumes:
  pgdata:

networks:
  banking-net:
